{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}-svc
  labels:
    app: {{ $service.name }}
spec:
  type: {{ $service.service.type }}
  selector:
    app: {{ $service.name }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.targetPort }}
{{- end }}
{{- end }}