apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  labels:
    app: {{ .Values.postgres.name }}
type: Opaque
data:
  postgres-root-username: {{ .Values.postgres.credentials.username | b64enc }}
  postgres-root-password: {{ .Values.postgres.credentials.password | b64enc }}