apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.postgres.name }}
  ports:
  - port: {{ .Values.postgres.service.port }}
    name: postgres